CONFIG_SRAM_SIZE=30
CONFIG_RETAINED_MEM=y
CONFIG_RETENTION=y
CONFIG_RETAINED_MEM_ZEPHYR_RAM=y
CONFIG_BOOT_SHARE_DATA=y
CONFIG_BOOT_SHARE_DATA_BOOTINFO=y
CONFIG_BOOT_SHARE_BACKEND_RETENTION=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y

CONFIG_PSA_CRYPTO_DRIVER_CRACEN=n

CONFIG_BOOT_IMAGE_EXECUTABLE_RAM_START=0x20000000
CONFIG_BOOT_IMAGE_EXECUTABLE_RAM_SIZE=523264

CONFIG_PSA_CRYPTO_DRIVER_OBERON=y


